name: CustomAlerts
main: CustomAlerts\CustomAlerts
version: 1.7.2
api: [3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.1, 3.0.2, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9]
load: STARTUP
author: EvolSoft & Zeao
description: "Customize alerts (join/leave messages, etc...)"
website: "http://www.evolsoft.tk"

commands:
  customalerts:
    aliases: ["calerts","ca"]
    description: CustomAlerts Master Command
    permission: customalerts
permissions:
  customalerts:
    default: op
    description: CustomAlerts Master Permission
    children:
      customalerts.help:
        default: op
        description: CustomAlerts command Help permission.
      customalerts.info:
        default: op
        description: CustomAlerts command Info permission.
      customalerts.reload:
        default: op
        description: CustomAlerts command Reload permission.
